### ISSUE TITLE
Add Member: duplicate initialMsg field?

### ISSUE THREAD

**Issue by cryptix** [ssbc/private-groups-spec#2]
Shouldn't `initialMsg` be equal to the root of the `group` and `members` tangles? Or even remove it?

**Comment by mixmix** [comment]
it should be a duplication of `tangles.group.root`, yes

Have fixed this and left a note in : b0b24a028508ce77681b629dad1dc9188bc20fae

Considerations:
- it doesn't cost much here
- in the future we may "cloak" the tangle cipherlinks, so having a plaintext key might be needed here

**Comment by mixmix** [comment]
I think this resolves this issue @cryptix , I've closed it.
If you think it's not a good solution feel free to reopen and can discuss more.

Really appreciate your close reading!

**Comment by cryptix** [comment]
> it doesn't cost much here

I’m leaning on the side of _why have an extra key that you could set wrong_ but I can live with it if we clearly spec that these three keys need to be equal.
